language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: nothingmi@muchencute.com
  on:
    tags: true
  api_key:
    secure: rVVo0PnQgiKMMp5MAdgYK3jN/FQarVdSGr1VU84Ji+M46UR5G3opISPOOHqOWjvIXb1cdpiOkVprPNhOL4SwrjrA0177rtOB0uV0uvW6oHEqAZKwa16XOGQIvxPp4nSA7AK8c9up5O8Vgajd0tpnVsmlQrn0wMXhzHg/zlVP/q9HU29y4gcWE1CQ2RV6E1xfFw3UxyVhLVp6dVcy8d47DTfQsT/0boRYbH+uMicr2VOU0fjLoYj3SOtqEDCtjDje4f7bDjeiJZf19dSsrideOpLNd81iChPoSI+MvWI2zz3LBFiDn0tdVcnuW3vIMz8vugf10NyrjYy25E8KHQrgoUpoUjyqk6wrg/YqQYAervH5/HeUny4wmE+0gKgjcPbnMAV8D1MHjuXenQx1R9rD5Toe3PZvmOJdibUYcuCsJmiiPTDxHsfzN5sH1okxPHo20NuTG6iU2N7o2chDisK6PVLaDd7+MkbUSHmxPMwJikHnAHMwVa/wIaOwiolszOXkRPEDljSnp4svf5InPkm1vRyYU5clILaoG3rjR26t+cvFvIL08H2DHdupF38OPjEWefY2ninWHfHWJ9bcBF6hf3LEAjih/6+ZorsjaOVWwAr3cF9Oz5DnMKUkqdsjXWQRgfVYZepVWFODkt26r3bzBYLqGFPC9z5VxkKimMRg+Dw=
