language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: "nothingmi@muchencute.com"
  api_key:
    secure: BTTWWz3rSR19MDmFuEagFdq2b1c0wEa0HV1XRi96HQeAs4j7uWDGYg4/shzVjFSqVkaZcu3lxHLitfZGAgkFeTj2adxp7oGtWt1r1YU30rYPq9gCR6dV4O6FERT8pfy/tnE7Wu4TGD7AYhGEhA4QqWs8uJvHMiBK9WiYpvIg0ngy9d1JSqvPbC7XK1aYiuse5rYCGnODcQ8YQs7DoPB4qYsFAi5fNJ+0poY69L72+cYpdA1rQNxQaVyFR86FJ1yFB0uwopXyqv3VgWmXDWDv2Z66QX60yWiJ/DI/xaR2CVK+19XSuwzynCmoKB9hE6By2kEzfvxS6Qy7Kr/l6/7xkxFMOeb7a6hL3cxGUrbt8UgS0k5c03rts8j5mJDudvewQk6bB7pY53NPVZeatc/RhCL528/zK//tIG/JRnA9f/w5j6vl8DP7TmOL7ebWZbMqeibp7/WSrEksW+lMZ2hYK2eWZ33eqdc+lJHvSFsrHUG084JtRnQhhK+HpWvbqmUcvWJuFvOkWIq11kGcpKfHF3fOpdMiSKaVYVye0/nfP7Dxsef3X84fsZ7mOtmZC5L5++QRKw0ybhZSzxU+93W7PcQyahqF7wsjFVC19k25WcMHaWXomO2yJYSK8PgNmBnqHZ5sTEeOhH5SnlU7q9zdq0yJx9YKGYQwLwVVk8G4w6Q=
