language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: nothingmi@muchencute.com
  on:
    tags: true
  api_key:
    secure: YO5Fo0vqFAjYeihrBwLAgguEidgdjPwmTXdfH+sNI4BNwSRZsb6VN1x5tqCCDu6pXgkG8D2DPYVc0gJZ/BKYUcHslkZUPONc8H+ivG6nq1vRkPZzyrGbrIrWKwFVYEPi/sykbkNY7GwJIlogEeulsTLqso/IW5E8Zta0q9uUtvAYPpBkSApxSojeS0GhFgjAUepNL3AOHnn01eclAgKfXB9eerHOVYMKmr9KqatzYNVvRsMmRUlRh3EaRWE6OMITi+N68E3HLmo2jUVvrFI80QbJr6m8SCxHK2JOKZTsDn/AMXOzMDJS+LXNko6ySqBTMZywv7sErG7nmww82FC9NLOZfm3WoNdx2dR26F7X+E8SyJl/vr98Zpe6BMK3qHdJ3zNj1U2hAdkY46dQErzQlytMzgmS/zcDR6oWhQVlpUkfTzjTUi5M+E+EaQ9YiC+JD8ctKDdSLTKfvLHd8gdJFlUnvYy5tOM6OjtzFZuU8DpUm2vsHvqc+xs9LiQ4HInLebDnXebFM3AdqZi1VRJg2C0YkoqOcIRbNLZk8UB0GbpzcFoTnj5IwaeN+QT79yF4HqMc+FJDJhj1YlbRn0Fcru/7iNzLfiVAkWTBm4pTTalsrl5RaMvpZEUze2HYbUWxQTavljI74zLgHG8ntehXijvF+NIuDqgT/8RG0QnCli4=
